--Create Warehouse
CREATE OR REPLACE WAREHOUSE RETAIL_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
--Create Database
CREATE OR REPLACE DATABASE RETAIL_DW;
--Use Database
USE DATABASE RETAIL_DW;
--Create Schemas
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA CURATED;
CREATE OR REPLACE SCHEMA ANALYTICS;
CREATE OR REPLACE SCHEMA AUDIT;
