--Create File Format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE;

--Create Internal Stage

USE SCHEMA RAW;

CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT = CSV_FORMAT;
