-- create file FORMAT

USE DATABASE RETAIL_DW;

CREATE OR REPLACE FILE FORMAT RETAIL_WH.CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE;

-- Create Internal Stage

USE SCHEMA RAW;

CREATE OR REPLACE RETAIL_WH.STAGE RETAIL_STAGE
FILE_FORMAT = CSV_FORMAT;

--verify

SHOW STAGES;

--check files after uploading in stage

LIST @RAW.RETAIL_STAGE;
